name: Deploy ADF to Dev Environment

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Validate and Generate ARM template
        run: npm run build export ${{ github.workspace }}/azure/adf/subscriptions/adf-dev
        working-directory: ${{ github.workspace }}/azure/adf

      - name: Run Update Triggers
        shell: pwsh
        run: ./cicd/adf_dev_update_trigger.ps1 ${{ github.workspace }}/azure/adf/ExportedArmTemplate.json

      # Upload artifact - old version (needs update)
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExportedArmTemplate
          path: ${{ github.workspace }}/azure/adf/ExportedArmTemplate

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      # Download previously uploaded artifact - old version (needs update)
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: ExportedArmTemplate

      - name: Login via Az module
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_NONPROD_CLIENT_ID }}
